[2023-08-13 10:40:39,619] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: submit_pyspark_script_to_emr.upload_script_to_s3 manual__2023-08-13T10:40:36.792331+00:00 [queued]>
[2023-08-13 10:40:39,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: submit_pyspark_script_to_emr.upload_script_to_s3 manual__2023-08-13T10:40:36.792331+00:00 [queued]>
[2023-08-13 10:40:39,633] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-13 10:40:39,634] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-13 10:40:39,634] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-13 10:40:39,650] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_script_to_s3> on 2023-08-13 10:40:36.792331+00:00
[2023-08-13 10:40:39,655] {standard_task_runner.py:52} INFO - Started process 360 to run task
[2023-08-13 10:40:39,660] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'submit_pyspark_script_to_emr', 'upload_script_to_s3', 'manual__2023-08-13T10:40:36.792331+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/orchestration/submit_spark_job_to_emr.py', '--cfg-path', '/tmp/tmpwqb80oc4', '--error-file', '/tmp/tmp6tdzcrcg']
[2023-08-13 10:40:39,662] {standard_task_runner.py:80} INFO - Job 3: Subtask upload_script_to_s3
[2023-08-13 10:40:39,733] {task_command.py:370} INFO - Running <TaskInstance: submit_pyspark_script_to_emr.upload_script_to_s3 manual__2023-08-13T10:40:36.792331+00:00 [running]> on host airflow_scheduler
[2023-08-13 10:40:39,857] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=submit_pyspark_script_to_emr
AIRFLOW_CTX_TASK_ID=upload_script_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-08-13T10:40:36.792331+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-13T10:40:36.792331+00:00
[2023-08-13 10:40:39,859] {submit_spark_job_to_emr.py:68} INFO - The fetched bucket is {{ ti.xcom_pull(task_ids='fetch_cluster_id_and_paramns', key='return_value')[5] }}
[2023-08-13 10:40:39,860] {submit_spark_job_to_emr.py:69} INFO - The fetched local filename is /opt/airflow/dagsdags/computation/src/pyspark_scripts/read_and_write_back_to_s3.py
[2023-08-13 10:40:39,861] {submit_spark_job_to_emr.py:70} INFO - The fetched S3 file destination is scripts/read_and_write_back_to_s3.py
[2023-08-13 10:40:39,874] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2023-08-13 10:40:39,876] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2023-08-13 10:40:39,877] {base_aws.py:100} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2023-08-13 10:40:39,952] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/orchestration/submit_spark_job_to_emr.py", line 73, in _local_to_s3
    s3.load_file(filename=filename, bucket_name=BUCKET_NAME, replace=True, key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 615, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/inject.py", line 148, in upload_file
    callback=Callback,
  File "/home/airflow/.local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 288, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 585, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
    self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
  File "/home/airflow/.local/lib/python3.7/site-packages/s3transfer/utils.py", line 247, in get_file_size
    return os.path.getsize(filename)
  File "/usr/local/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dagsdags/computation/src/pyspark_scripts/read_and_write_back_to_s3.py'
[2023-08-13 10:40:39,968] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=submit_pyspark_script_to_emr, task_id=upload_script_to_s3, execution_date=20230813T104036, start_date=20230813T104039, end_date=20230813T104039
[2023-08-13 10:40:39,981] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task upload_script_to_s3 ([Errno 2] No such file or directory: '/opt/airflow/dagsdags/computation/src/pyspark_scripts/read_and_write_back_to_s3.py'; 360)
[2023-08-13 10:40:40,033] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-13 10:40:40,070] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
